name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential cmake fakeroot dpkg-dev libcurl4-openssl-dev
          wget https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h -O src/httplib.h
      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Check version
        run: |
          if [ -z "${{ env.VERSION }}" ]; then
            echo "VERSION file is missing or empty!"
            exit 1
          fi

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Create Debian package structure
        run: |
          mkdir -p pkg/usr/local/bin
          cp build/mcp_server pkg/usr/local/bin/
          mkdir -p pkg/DEBIAN
          cat <<EOF > pkg/DEBIAN/control
          Package: mcp-server
          Version: ${{ env.VERSION }}
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <you@example.com>
          Description: MCP Server (Model Context Protocol) with LLM relay
          EOF

      - name: Build Debian package
        run: dpkg-deb --build pkg mcp-server_${{ env.VERSION }}_amd64.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server-deb
          path: mcp-server_${{ env.VERSION }}_amd64.deb