name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.2'

      - name: Install dependencies
        run: sudo apt-get install -y debhelper

      - name: Create build directory
        run: mkdir build && cd build

      - name: Run CMake
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build .

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create Debian package
        run: |
          cd debian
          dpkg-buildpackage -us -uc -b

      - name: Upload Debian package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: ../*.deb